[package]
name = "rust_sandbox"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.3", features = ["derive"] }
regex = "1.9.5"
reqwest = { version = "0.11", features = ["blocking"] }
